local map = vim.api.nvim_set_keymap

vim.g.mapleader = " "

map("n", "<leader>g", [[:DiffviewToggle<CR>]], {})
map("n", "<leader>n", [[:NvimTreeToggle<CR>]], {})
map("n", "<leader>t", [[:TroubleToggle<CR>]], {})
map("n", "<leader>/", [[:CommentToggle<CR>]], {})
map("v", "<leader>/", [[:CommentToggle<CR>]], {})
map("n", "<leader>f", [[:Telescope find_files<CR>]], {})
map("n", "<leader>b", [[:Telescope buffers<CR>]], {})
map("n", "<leader>g", [[:Telescope live_grep<CR>]], {})
map("n", "<leader>cs", [[:Telescope colorscheme<CR>]], {})
map("i", "<C-c>", "<C-O>:stopinsert<CR>", {})
map('n', '<C-S-Up>', ':MoveLine(-1)<CR>', {})
map('n', '<C-S-Down>', ':MoveLine(1)<CR>', {})
map('n', '<C-S-Left>', ':MoveHChar(-1)<CR>', {})
map('n', '<C-S-Right>', ':MoveHChar(1)<CR>', {})
map('v', '<C-S-Up>', ':MoveBlock(-1)<CR>', {})
map('v', '<C-S-Down>', ':MoveBlock(1)<CR>', {})
map('v', '<C-S-Left>', ':MoveHBlock(-1)<CR>', {})
map('v', '<C-S-Right>', ':MoveHBlock(1)<CR>', {})
map("i", "<C-S-Up>", "<Esc>:m .-2<CR>==gi", {})
map("i", "<C-S-Down>", "<Esc>:m .+1<CR>==gi", {})
map("v", "<leader>y", '"+y', {})
map("n", "<leader>w", ":bd<CR>", {})
map("n", "<leader>W", ":%bd<CR>", {})
map("n", "<leader>v", ":vsplit<CR>", {})
map("n", "<leader>h", ":split<CR>", {})
-- map("n", "<C-d>", "<C-d>zz", {})
-- map("n", "<C-u>", "<C-u>zz", {})
-- map("n", "<C-S-Left>", ":wincmd h<CR>", {})
-- map("n", "<C-S-Right>", ":wincmd l<CR>", {})
-- map("n", "<C-S-Up>", ":wincmd k<CR>", {})
-- map("n", "<C-S-Down>", ":wincmd j<CR>", {})
