#!/bin/bash

ENVDIR="$( cd "$( dirname "$0" )" && pwd )"
COMPONENT=$1
SCOPE=$ENVDIR/$COMPONENT

# Run bootstrap.sh from each component or from supplied component
find $SCOPE -name bootstrap.sh | xargs bash
