#!/bin/bash

ENVDIR="$( cd "$( dirname "$0" )" && pwd )"
COMPONENT=$1
SCOPE=$ENVDIR/$COMPONENT

# Run bootstrap.sh from each component or from supplied component
for bootstrapper in $(find $SCOPE -name bootstrap.sh); do
  bash "$bootstrapper"
done
