#!/bin/bash

ENVDIR="$( cd "$( dirname "$0" )" && pwd )"

source $ENVDIR/aliases
config config status.showUntrackedFiles no
git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"

# Source env.zsh from each component or from supplied component
for envfile in $(find $ENVDIR -name env.zsh); do
  source $envfile
done
