#!/bin/bash

ENVDIR="$( cd "$( dirname "$0" )" && pwd )"

export PATH="$HOME/.env/bin:$HOME/.tools/bin:$PATH"

source $ENVDIR/aliases
config config status.showUntrackedFiles no
git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"

export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK="/run/user/$UID/gnupg/S.gpg-agent.ssh"
gpg-connect-agent updatestartuptty /bye > /dev/null

# Source env.zsh from each component or from supplied component
for envfile in $(find $ENVDIR -name env.zsh); do
  source $envfile
done
