#!/bin/bash

DIR="$( cd "$( dirname "$0" )" && pwd )"

# Install packages from packages-system
SYSTEM_PACKAGES=$(cat $DIR/packages/system | sed 's/\\n/ /')
sudo dnf install -y $SYSTEM_PACKAGES

# Set default shell for user
sudo usermod --shell /usr/bin/zsh $USER
