import = [
  "/Users/jarred/.config/yarn/global/node_modules/alacritty-themes/themes/Catppuccin-Mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14

  [font.bold]
  family = "VictorMono Nerd Font"
  style = "Bold"

  [font.italic]
  family = "VictorMono Nerd Font"
  style = "SemiBold Italic"

  [font.normal]
  family = "VictorMono Nerd Font"
  style = "SemiBold"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
opacity = 1
decorations = "Buttonless"

  [window.padding]
  x = 0
  y = 0
