import = [
  "/Users/jarred/.tools/n/lib/node_modules/alacritty-themes/themes/Catppuccin-Mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 13

  [font.bold]
  family = "JetBrainsMono Nerd Font"
  style = "Bold"

  [font.italic]
  family = "JetBrainsMono Nerd Font"
  style = "Italic"

  [font.normal]
  family = "JetBrainsMono Nerd Font"
  style = "Regular"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "buttonless"
opacity = 1

  [window.padding]
  x = 0
  y = 0
