import = [
  "/Users/jarred/.config/yarn/global/node_modules/alacritty-themes/themes/Tomorrow.dark.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 12

  [font.bold]
  family = "Liga SFMono Nerd Font"
  style = "Bold Italic"

  [font.italic]
  family = "Liga SFMono Nerd Font"
  style = "Italic"

  [font.normal]
  family = "Liga SFMono Nerd Font"
  style = "Regular"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
opacity = 1
decorations = "None"

  [window.padding]
  x = 6
  y = 6
